# Generated by Django 2.2.6 on 2019-11-09 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('visao', models.TextField(verbose_name='Visao')),
                ('sequencia_maxima', models.FloatField(blank=True, null=True, verbose_name='Sequência máxima')),
                ('soma_quadrados_pesos', models.FloatField(blank=True, null=True, verbose_name='Soma quadrados dos Pesos')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TermoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coletado_em', models.DateField(auto_now=True, verbose_name='Coletado em:')),
                ('url', models.URLField(verbose_name='Url')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletor.Host')),
            ],
        ),
        migrations.CreateModel(
            name='IndiceInvertido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Peso')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletor.Documento')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletor.TermoDocumento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coletor.Link'),
        ),
    ]
