# Generated by Django 2.2.6 on 2019-11-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='coletado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Coletado em:'),
        ),
    ]
