# Generated by Django 2.2.6 on 2019-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletor', '0003_auto_20191111_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
